#!/bin/bash
# services.sh v0.3 - Systemd service management

set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/common.sh"

# Check if deb package systemd template exists
has_deb_package_template() {
    [[ -f /usr/lib/systemd/system/code-server@.service ]]
}

# Install code-server systemd service
install_code_server_service() {
    log_info "Installing code-server systemd service..."
    
    # Detect code-server binary path
    local codeserver_bin
    codeserver_bin=$(detect_codeserver_binary) || error_exit "code-server binary not found"
    
    if has_deb_package_template; then
        log_info "Detected deb package systemd template, using override method"
        
        if [[ $DRY_RUN -eq 1 ]]; then
            log_info "[DRY-RUN] Would create systemd override"
            return 0
        fi
        
        local override_dir="/etc/systemd/system/code-server@.service.d"
        mkdir -p "$override_dir"

        if [[ -f "${override_dir}/local.conf" ]]; then
            backup_file "${override_dir}/local.conf"
        fi

        cat > "${override_dir}/local.conf" <<EOF
# Local customization for code-server
# Generated by wscode installer v${VERSION}

[Unit]
Description=code-server for %i
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
User=%i

# Clear default ExecStart
ExecStart=

# Validation and config generation before starting
ExecStartPre=/bin/bash -c 'id %i > /dev/null || exit 1'
ExecStartPre=/bin/bash -c 'uid=$(id -u %i); [ $((20000 + uid)) -le 65535 ] || exit 1'
ExecStartPre=/bin/bash -c 'home=$(getent passwd %i | cut -d: -f6); [ -n "$home" ] || exit 1; mkdir -p "$home/.local/share/code-server/extensions"'
ExecStartPre=/bin/bash -c 'home=$(getent passwd %i | cut -d: -f6); uid=$(id -u %i); port=$((20000 + uid)); mkdir -p "$home/.config"; echo "bind-addr: 127.0.0.1:$port" > "$home/.config/code-server/config.yaml"; echo "auth: none" >> "$home/.config/code-server/config.yaml"'

# Start code-server (config file determines bind-addr)
ExecStart=${codeserver_bin}

# Restart policy
Restart=on-failure
RestartSec=10
StartLimitInterval=350
StartLimitBurst=10

[Install]
WantedBy=multi-user.target
EOF
        chmod 644 "${override_dir}/local.conf"
        log_success "Created systemd override at ${override_dir}/local.conf"
        
    else
        log_info "No deb package template found, installing custom template"
        
        local template_file="${TEMPLATE_DIR}/code-server@.service.tpl"
        local service_file="/etc/systemd/system/code-server@.service"
        
        if [[ ! -f "$template_file" ]]; then
            error_exit "Template file not found: $template_file"
        fi
        
        if [[ -f "$service_file" ]]; then
            backup_file "$service_file"
        fi
        
        if [[ $DRY_RUN -eq 1 ]]; then
            log_info "[DRY-RUN] Would install $service_file"
            return 0
        fi
        
        sed "s|{{CODESERVER_BIN}}|${codeserver_bin}|g" "$template_file" > "$service_file"
        chmod 644 "$service_file"
        
        log_success "Installed custom systemd service: $service_file"
    fi
}

# Install hardening overrides
install_code_server_hardening() {
    log_info "Installing code-server hardening overrides..."
    
    local template_file="${TEMPLATE_DIR}/code-server@.override-hardening.conf.tpl"
    local override_dir="/etc/systemd/system/code-server@.service.d"
    local override_file="${override_dir}/hardening.conf"
    
    if [[ ! -f "$template_file" ]]; then
        log_warn "Hardening template not found: $template_file"
        return 0
    fi
    
    if [[ -f "$override_file" ]]; then
        backup_file "$override_file"
    fi
    
    if [[ $DRY_RUN -eq 1 ]]; then
        log_info "[DRY-RUN] Would install $override_file"
        return 0
    fi
    
    mkdir -p "$override_dir"

    cp "$template_file" "$override_file"
    chmod 644 "$override_file"
    
    log_success "Hardening overrides installed"
}

# Enable and start code-server for a user
enable_code_server_for_user() {
    local user="$1"
    
    log_info "Enabling code-server for user: $user"
    
    if ! user_exists "$user"; then
        log_error "User $user does not exist"
        return 1
    fi
    
    # Validate port
    local port
    port=$(get_user_port "$user")
    validate_port "$port"
    
    local service="code-server@${user}.service"
    
    if [[ $DRY_RUN -eq 1 ]]; then
        log_info "[DRY-RUN] Would enable and start $service"
        return 0
    fi
    
    if ! systemctl is-enabled "$service" &> /dev/null; then
        systemctl enable "$service"
        log_debug "Enabled $service"
    fi
    
    if systemctl is-active "$service" &> /dev/null; then
        systemctl restart "$service"
        log_debug "Restarted $service"
    else
        systemctl start "$service"
        log_debug "Started $service"
    fi
    
    sleep 2

    if ! systemctl is-active "$service" &> /dev/null; then
        log_error "Failed to start $service"
        systemctl status "$service" --no-pager || true
        return 1
    fi
    
    log_success "code-server enabled and running for $user"
    return 0
}

# Setup code-server for all users
setup_code_server_services() {
    log_info "=== Setting up code-server services ==="

    install_code_server_service
    install_code_server_hardening

    if [[ $DRY_RUN -eq 0 ]]; then
        systemctl daemon-reload
    fi

    local users
    mapfile -t users < <(get_enabled_users)
    
    if [[ ${#users[@]} -eq 0 ]]; then
        log_warn "No users to enable code-server for"
        return 0
    fi
    
    log_info "Enabling code-server for ${#users[@]} user(s)"
    
    local failed=0
    for user in "${users[@]}"; do
        if ! enable_code_server_for_user "$user"; then
            ((failed++))
        fi
    done
    
    if [[ $failed -gt 0 ]]; then
        log_error "Failed to enable code-server for $failed user(s)"
        return 1
    fi
    
    log_success "=== code-server services setup completed ==="
    return 0
}
